apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: person-service
build:
  artifacts:
    - image: person-service
      jib:
        project: pl.piomin.services:claude-ai-spring-boot
        args:
          - -Djib.to.image=person-service:latest
manifests:
  rawYaml:
    - k8s/configmap.yml
    - k8s/secret.yml
    - k8s/deployment.yml
    - k8s/service.yml
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: person-service
    port: 8080
    localPort: 8080
